Fix missing workername
flower   -> flower:0.9.0 tornado:4.2 babel:2.2.0
software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:3.5.1
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:djcelery.backends.database:DatabaseBackend

Traceback (most recent call last):
  File "../venv/lib/python3.5/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "../venv/lib/python3.5/site-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "../venv/lib/python3.5/site-packages/flower/views/tasks.py", line 56, in get
    task['worker'] = task['worker'].hostname
AttributeError: 'NoneType' object has no attribute 'hostname'